server:
  port: 8080
spring:
  application:
    name: MALL-WEB
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8000/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
feign:
  hystrix:
    enabled: true